apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-ingress-rule
  namespace: project-jenkins
  annotations:
    kubernetes.io/ingress.class: public-nginx           
    nginx.ingress.kubernetes.io/ssl-redirect: "false"       
spec:
  rules:
  - host: jenkinsproject01.alokeg.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: project-jenkins-service
            port:
              number: 80